### ISSUE TITLE
some times it will lose the connection

### ISSUE THREAD

**Issue by XDID** [iamcco/markdown-preview.nvim#107] opened 2019-12-02 07:39 UTC

**Comment by iamcco** [comment] 2019-12-03 02:53
Any way to reproduce ?

**Comment by stevenwalton** [comment] 2020-01-27 03:04
I'm experiencing this problem as well. It appears to be random, I'm having a hard time reproducing. I take the default settings. 

Mostly I notice it dropping when I'm writing LaTeX, but that isn't a necessary condition. Many times the session will drop even if I haven't typed anything, it is just sitting there while I'm looking at a different webpage (FireFox). I'm not very familiar with vim script but if you can tell me how to produce a log file I'd be happy to add and help debug (I seriously love this plugin. Saves me a lot of time and commits). 

Environment:
vim cli
Firefox 71
Ubuntu 18.04

**Comment by iamcco** [comment] 2020-01-27 08:33
@stevenwalton You should set `let g:mkdp_auto_close = 0` to disable auto close by switch buffer.

**Comment by stevenwalton** [comment] 2020-01-28 02:39
That solves the issue for me. I'm not sure if this explains all the random stops so give me 24hrs before marking as resolved. But this probably resolves the issue.

side notes: 
1) is there a help page? `:help mkdp` and `:help MarkdownPreview` don't exist. 

2) should this variable default to 0? I'm not sure what workflows are like in neovim, but a workflow in vim your open buffers should be things you're working on. So it should close when the buffer quits, but not because you're switching buffers (kinda defeats the purpose of panes, buffers, and tabs).

**Comment by stevenwalton** [comment] 2020-01-28 20:12
I'm confident that this was the error now. I haven't experienced any dropping since setting auto close to 0.

**Comment by iamcco** [comment] 2020-02-04 10:23
> should this variable default to 0? 

Will not change the default since it will effect many user. If use chrome it will close the preview page, but for firefox you have to change firefox settings to allow javascript to close web page. So the default behavior for firefox seems that it will lose connection that switch buffer when the option on.

**Comment by iamcco** [comment] 2020-03-01 10:53
Close, reopen if you still have the problem.

**Closed by iamcco** 2020-03-01 10:53 UTC
Labels: question
